import { IProjects, IUser } from "../Interfaces/appInterfaces";

export const UserActions=["---","delete","revoke","profile"];

export const ProjectActions=["---","delete","Bidders"];
export const userData: IUser[] = [
    {
      Address: ["Marble hall", "Lebowakgom"],
      AdvertisingMsg: 'bio',
      certificate: '',
      companyEmail: 'someone@gmail.com',
      companyName: "my awsome company",
      formSubmitted: 'contractor',
      Id: 'dssfsdffddgdfd',
      imgfilename: 'xxzzxzx',
      isactive: 'no',
      membership: 'contractor',
      pdffilename: 'vfdvfdvfdf',
      phone: '0760170950',
      profileImage: 'http://dfddfd',
      RegistrationNo: 'QS124686Y',
      Services: ["hhgfhh"],
      tncs: 'yes',
      YourID: 'dssfsdffddgdfd',
      YourName: 'someone',
      YourSurName: 'Random  Surname'
    },
    {
      Address: ["Marble hall", "Lebowakgom"],
      AdvertisingMsg: 'bio',
      certificate: '',
      companyEmail: 'someone@gmail.com',
      companyName: "my awsome company",
      formSubmitted: 'contractor',
      Id: 'dssfsdffddgdfd',
      imgfilename: 'xxzzxzx',
      isactive: 'yes',
      membership: 'contractor',
      pdffilename: 'vfdvfdvfdf',
      phone: '0760170950',
      profileImage: 'http://dfddfd',
      RegistrationNo: '12343d453',
      Services: ["hhgfhh"],
      tncs: 'yes',
      YourID: 'dssfsdffddgdfd',
      YourName: 'someone',
      YourSurName: 'Random  Surname'
    },
    {
      Address: ["Marble hall", "Lebowakgom"],
      AdvertisingMsg: 'bio',
      certificate: '',
      companyEmail: 'someone@gmail.com',
      companyName: "my awsome company",
      formSubmitted: 'contractor',
      Id: 'dssfsdffddgdfd',
      imgfilename: 'xxzzxzx',
      isactive: 'no',
      membership: 'contractor',
      pdffilename: 'vfdvfdvfdf',
      phone: '0760170950',
      profileImage: 'http://dfddfd',
      RegistrationNo: 'ff12343d43',
      Services: ["hhgfhh"],
      tncs: 'yes',
      YourID: 'dssfsdffddgdfd',
      YourName: 'someone',
      YourSurName: 'Random  Surname'
    },
    {
      Address: ["Marble hall", "Lebowakgom"],
      AdvertisingMsg: 'bio',
      certificate: '',
      companyEmail: 'someone@gmail.com',
      companyName: "my awsome company",
      formSubmitted: 'contractor',
      Id: 'dssfsdffddgdfd',
      imgfilename: 'xxzzxzx',
      isactive: 'no',
      membership: 'contractor',
      pdffilename: 'vfdvfdvfdf',
      phone: '0760170950',
      profileImage: 'http://dfddfd',
      RegistrationNo: '',
      Services: ["hhgfhh"],
      tncs: 'yes',
      YourID: 'dssfsdffddgdfd',
      YourName: 'someone',
      YourSurName: 'Random  Surname'
    },
    {
      Address: ["Marble hall", "Lebowakgom"],
      AdvertisingMsg: 'bio',
      certificate: '',
      companyEmail: 'someone@gmail.com',
      companyName: "my awsome company",
      formSubmitted: 'contractor',
      Id: 'dssfsdffddgdfd',
      imgfilename: 'xxzzxzx',
      isactive: 'yes',
      membership: 'contractor',
      pdffilename: 'vfdvfdvfdf',
      phone: '0760170950',
      profileImage: 'http://dfddfd',
      RegistrationNo: '',
      Services: ["hhgfhh"],
      tncs: 'yes',
      YourID: 'dssfsdffddgdfd',
      YourName: 'someone',
      YourSurName: 'Random  Surname'
    },
    {
      Address: ["Marble hall", "Lebowakgom"],
      AdvertisingMsg: 'bio',
      certificate: '',
      companyEmail: 'someone@gmail.com',
      companyName: "my awsome company",
      formSubmitted: 'contractor',
      Id: 'dssfsdffddgdfd',
      imgfilename: 'xxzzxzx',
      isactive: 'yes',
      membership: 'contractor',
      pdffilename: 'vfdvfdvfdf',
      phone: '0760170950',
      profileImage: 'http://dfddfd',
      RegistrationNo: '12343d453',
      Services: ["hhgfhh"],
      tncs: 'yes',
      YourID: 'dssfsdffddgdfd',
      YourName: 'someone',
      YourSurName: 'Random  Surname'
    },
    {
      Address: ["Marble hall", "Lebowakgom"],
      AdvertisingMsg: 'bio',
      certificate: '',
      companyEmail: 'someone@gmail.com',
      companyName: "my awsome company",
      formSubmitted: 'contractor',
      Id: 'dssfsdffddgdfd',
      imgfilename: 'xxzzxzx',
      isactive: 'no',
      membership: 'contractor',
      pdffilename: 'vfdvfdvfdf',
      phone: '0760170950',
      profileImage: 'http://dfddfd',
      RegistrationNo: '',
      Services: ["hhgfhh"],
      tncs: 'yes',
      YourID: 'dssfsdffddgdfd',
      YourName: 'someone',
      YourSurName: 'Random  Surname'
    },
    {
      Address: ["Marble hall", "Lebowakgom"],
      AdvertisingMsg: 'bio',
      certificate: '',
      companyEmail: 'someone@gmail.com',
      companyName: "my awsome company",
      formSubmitted: 'contractor',
      Id: 'dssfsdffddgdfd',
      imgfilename: 'xxzzxzx',
      isactive: 'no',
      membership: 'contractor',
      pdffilename: 'vfdvfdvfdf',
      phone: '0760170950',
      profileImage: 'http://dfddfd',
      RegistrationNo: '',
      Services: ["hhgfhh"],
      tncs: 'yes',
      YourID: 'dssfsdffddgdfd',
      YourName: 'someone',
      YourSurName: 'Random  Surname'
    },
    {
      Address: ["Marble hall", "Lebowakgom"],
      AdvertisingMsg: 'bio',
      certificate: '',
      companyEmail: 'someone@gmail.com',
      companyName: "my awsome company",
      formSubmitted: 'contractor',
      Id: 'dssfsdffddgdfd',
      imgfilename: 'xxzzxzx',
      isactive: 'no',
      membership: 'contractor',
      pdffilename: 'vfdvfdvfdf',
      phone: '0760170950',
      profileImage: 'http://dfddfd',
      RegistrationNo: '',
      Services: ["hhgfhh"],
      tncs: 'yes',
      YourID: 'dssfsdffddgdfd',
      YourName: 'someone',
      YourSurName: 'Random  Surname'
    },
    {
      Address: ["Marble hall", "Lebowakgom"],
      AdvertisingMsg: 'bio',
      certificate: '',
      companyEmail: 'future@gmail.com',
      companyName: "my awsome company",
      formSubmitted: 'contractor',
      Id: 'dssfsdffddgdfd',
      imgfilename: 'xxzzxzx',
      isactive: 'no',
      membership: 'contractor',
      pdffilename: 'vfdvfdvfdf',
      phone: '0760170950',
      profileImage: 'http://dfddfd',
      RegistrationNo: '',
      Services: ["hhgfhh"],
      tncs: 'yes',
      YourID: 'dssfsdffddgdfd',
      YourName: 'someone',
      YourSurName: 'Random  Surname'
    },
    {
      Address: ["Marble hall", "Lebowakgom"],
      AdvertisingMsg: 'bio',
      certificate: '',
      companyEmail: 'dave@gmail.com',
      companyName: "my awsome company",
      formSubmitted: 'contractor',
      Id: 'kkgffg',
      imgfilename: 'xxzzxzx',
      isactive: 'no',
      membership: 'contractor',
      pdffilename: 'vfdvfdvfdf',
      phone: '0760170950',
      profileImage: 'http://dfddfd',
      RegistrationNo: '11111111',
      Services: ["hhgfhh"],
      tncs: 'yes',
      YourID: 'dssfsdffddgdfd',
      YourName: 'someone',
      YourSurName: 'Random  Surname'
    }
    // Add more data if needed
  ];

export const projectData:IProjects[]=[
  {
    addrs:"Benoni",
    AllcontactorKeys:[],
    bestOffer:"0.00",
    bstOffrId:"dsdsxw",
    budget:"500.98",
    description:"Need a capenter asap",
    email:"futurekgaphola@gmail.com",
    otherOffers:[],
    owner:'future',
    ownerId:"ssssss",
    phone:"0760170950",
    postTime:"14 April 2024",
    Profpic:'https://sfggh',
    ProjectId:"eeeee",
    Status:'open',
    task:'capentry',
    tncs:'yes',
    winnerId:"wsgfgdf"

  },
  {
    addrs:"Benoni",
    AllcontactorKeys:[],
    bestOffer:"0.00",
    bstOffrId:"dsdsxw",
    budget:"445.98",
    description:"Need a capenter asap",
    email:"futurekgaphola@gmail.com",
    otherOffers:[],
    owner:'future',
    ownerId:"ssssss",
    phone:"0760170950",
    postTime:"14 April 2024",
    Profpic:'https://sfggh',
    ProjectId:"eeeee",
    Status:'open',
    task:'capentry',
    tncs:'yes',
    winnerId:"wsgfgdf"

  }
  ,{
    addrs:"Benoni",
    AllcontactorKeys:[],
    bestOffer:"0.00",
    bstOffrId:"dsdsxw",
    budget:"874.98",
    description:"Need a capenter asap",
    email:"futurekgaphola@gmail.com",
    otherOffers:[],
    owner:'future',
    ownerId:"ssssss",
    phone:"0760170950",
    postTime:"14 April 2024",
    Profpic:'https://sfggh',
    ProjectId:"eeeee",
    Status:'open',
    task:'capentry',
    tncs:'yes',
    winnerId:"wsgfgdf"

  },
  {
    addrs:"Benoni",
    AllcontactorKeys:[],
    bestOffer:"0.00",
    bstOffrId:"dsdsxw",
    budget:"200.98",
    description:"Need a capenter asap",
    email:"futurekgaphola@gmail.com",
    otherOffers:[],
    owner:'future',
    ownerId:"ssssss",
    phone:"0760170950",
    postTime:"14 April 2024",
    Profpic:'https://sfggh',
    ProjectId:"eeeee",
    Status:'closed',
    task:'capentry',
    tncs:'yes',
    winnerId:"wsgfgdf"

  },
  {
    addrs:"Benoni",
    AllcontactorKeys:[],
    bestOffer:"0.00",
    bstOffrId:"dsdsxw",
    budget:"871.98",
    description:"Need a capenter asap",
    email:"futurekgaphola@gmail.com",
    otherOffers:[],
    owner:'future',
    ownerId:"ssssss",
    phone:"0760170950",
    postTime:"14 April 2024",
    Profpic:'https://sfggh',
    ProjectId:"eeeee",
    Status:'open',
    task:'capentry',
    tncs:'yes',
    winnerId:"wsgfgdf"

  },
  {
    addrs:"Benoni",
    AllcontactorKeys:[],
    bestOffer:"0.00",
    bstOffrId:"dsdsxw",
    budget:"874.98",
    description:"Need a capenter asap",
    email:"futurekgaphola@gmail.com",
    otherOffers:[],
    owner:'future',
    ownerId:"ssssss",
    phone:"0760170950",
    postTime:"14 April 2024",
    Profpic:'https://sfggh',
    ProjectId:"eeeee",
    Status:'open',
    task:'capentry',
    tncs:'yes',
    winnerId:"wsgfgdf"

  },
  {
    addrs:"Benoni",
    AllcontactorKeys:[],
    bestOffer:"0.00",
    bstOffrId:"dsdsxw",
    budget:"430.00",
    description:"Need a capenter asap",
    email:"futurekgaphola@gmail.com",
    otherOffers:[],
    owner:'future',
    ownerId:"ssssss",
    phone:"0760170950",
    postTime:"14 April 2024",
    Profpic:'https://sfggh',
    ProjectId:"eeeee",
    Status:'open',
    task:'capentry',
    tncs:'yes',
    winnerId:"wsgfgdf"

  }
]

